# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require "./app_config.rb"

default_platform(:android)

platform :android do
  before_all do |lane, options|
    # Skip the creation of the fastlane/README.md file when running fastlane
    skip_docs
  end

  desc "Lane envoked by jenkins"
  lane :jenkins do |options|
    config_url = options[:config_url]
    begin
      configurator = AppConfig.new(mode: URLMode::HTTP_LINK, url: config_url)
    rescue JSON::ParserError => e
      UI.user_error!("Fail to parse json: " + e.message + "\n" + "json url: #{config_url}")
    end
    configurator.mapped_platforms_properties.map { |properties| go_gradle(properties: properties) }
  end

  desc "Primary lane for build app(s)"
  lane :build_all_app do |options|

    platforms = options[:platforms]

    begin
      configurator = AppConfig.new(mode: URLMode::FILE_PATH, url: "./config.json", str_platforms: platforms)
    rescue JSON::ParserError => e
      UI.user_error!("Fail to parse json: " + e.message)
    end
    
    if configurator.zero_platform_mapped
      arr_platforms = configurator.split_platform
      UI.user_error!("無法對映到任何平台，打包中止: #{arr_platforms}")
    else
      configurator.mapped_platforms_properties.map { |properties| go_gradle(properties: properties) }
    end
  end

  desc "A demo lane for check"
  lane :spplat1 do |options|
    build_android_app(
      task: "assemble",
      build_type: "Release",
      flavor: "spplat1",
      project_dir: File.realpath("#{Dir.pwd}/../"),
      print_command: true,
      properties: {
        "android.injected.signing.store.file" => "#{Dir.pwd}/../signKey/key3.jks",
        "android.injected.signing.store.password" => "desheng@2020",
        "android.injected.signing.key.alias" => "fungame",
        "android.injected.signing.key.password" => "desheng@2020",
        "versionCode" => 100,
        "versionName" => "1.2.3",
      }
    )
  end

  desc "For gradle build"
  private_lane :go_gradle do |options|
    properties = options[:properties]
    build_android_app(
      task: "assemble",
      build_type: "Release",
      flavor: "fastlane",
      project_dir: File.realpath("#{Dir.pwd}/../"),
      print_command: true,
      properties: properties
    )
  end
end
