# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require_relative "./app_config.rb"

default_platform(:android)

platform :android do
  before_all do |lane, options|
    # Skip the creation of the fastlane/README.md file when running fastlane
    skip_docs
  end

  desc "Primary lane for build app(s)"
  lane :build_all_app do |options|
    platforms = options[:platforms]

    configurator = AppConfig.new
    if configurator.zero_platform_mapped(platforms)
      arr_platforms = configurator.split_platform(platforms)
      puts "無法對映到任何平台，打包中止: #{arr_platforms}"
    else
      configurator.mapping_platforms(platforms).each do |platform_info|
        properties = {}
        # add keystore info
        properties = properties.merge(AppConfig::KEY_STORE)
        properties = properties.merge({
          "fastlane_version_name" => configurator.dictionary_version,
          "fastlane_version_code" => configurator.short_version,
          "fastlane_app_code" => platform_info["app_code"],
          "fastlane_app_name" => platform_info["app_name"], 
          "fastlane_application_id" => platform_info["appid"], 
          "fastlane_jpush_appkey" => platform_info["jpush_appKey"],
          "fastlane_jpush_channel" => "developer-default",
          "fastlane_jpush_provider" => platform_info["appid"] + ".DataProvider",
          "fastlane_jpush_permission" => platform_info["appid"] + ".permission.JPUSH_MESSAGE", 
          "fastlane_security_config" => "@xml/test_network_security_config", 
          "fastlane_res_src_dir" => "src/platform/#{platform_info["app_code"]}/res"
        })

        go_gradle(properties: properties)
      end
    end
  end

  desc "A demo lane for check"
  lane :app do |options|
    build_android_app(
      task: "assemble",
      build_type: "Release",
      flavor: "app",
      project_dir: File.realpath("#{Dir.pwd}/../"),
      print_command: true,
      properties: {
        "android.injected.signing.store.file" => "#{Dir.pwd}/../signKey/key3.jks",
        "android.injected.signing.store.password" => "desheng@2020",
        "android.injected.signing.key.alias" => "fungame",
        "android.injected.signing.key.password" => "desheng@2020",
      }
    )
  end

  desc "For gradle build"
  private_lane :go_gradle do |options|
    properties = options[:properties]
    build_android_app(
      task: "assemble",
      build_type: "Release",
      flavor: "fastlane",
      project_dir: File.realpath("#{Dir.pwd}/../"),
      print_command: true,
      properties: properties
    )
  end
end
