package org.cxct.sportlottery.network.user.info


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass import org.cxct.sportlottery.common.proguards.KeepMembers
import org.cxct.sportlottery.network.common.UserGameTypeDiscount
import org.cxct.sportlottery.network.common.UserRebate

@JsonClass(generateAdapter = true) @KeepMembers
data class UserInfoData(
    @Json(name = "bankName") val bankName: String?,
    @Json(name = "cardNo") val cardNo: String?,
    @Json(name = "email") val email: String?,
    @Json(name = "facebook") val facebook: String?,
    @Json(name = "fullName") val fullName: String?,
    @Json(name = "hideFlag") val hideFlag: Int?,
    @Json(name = "iconUrl") val iconUrl: String?,
    @Json(name = "lastLoginIp") val lastLoginIp: String,
    @Json(name = "lastLoginTime") val lastLoginTime: Long?,
    @Json(name = "loginIp") val loginIp: String,
    @Json(name = "loginTime") val loginTime: Long,
    @Json(name = "nickName") val nickName: String,
    @Json(name = "phone") val phone: String,
    @Json(name = "platformId") val platformId: Long,
    @Json(name = "qq") val qq: String?,
    @Json(name = "remark") val remark: String?,
    @Json(name = "roleId") val roleId: Int?,
    @Json(name = "setted") val setted: Int,
    @Json(name = "subAddress") val subAddress: String?,
    @Json(name = "superId") val superId: Int,
    @Json(name = "superUserName") val superUserName: String,
    @Json(name = "telegram") val telegram: String?,
    @Json(name = "testFlag") val testFlag: Long,
    @Json(name = "updatePayPw") val updatePayPw: Int,
    @Json(name = "updatePw") val updatePw: Int,
    @Json(name = "userId") val userId: Long,
    @Json(name = "userLevelId") val userLevelId: Int,
    @Json(name = "userName") val userName: String,
    @Json(name = "userRebateList") val userRebateList: List<UserRebate>?,
    @Json(name = "userType") val userType: String,
    @Json(name = "wechat") val wechat: String?,
    @Json(name = "whatsapp") val whatsapp: String?,
    @Json(name = "zalo") val zalo: String?,
    @Json(name = "growth") val growth: Long?,
    @Json(name = "maxBetMoney") val maxBetMoney: Long?,
    @Json(name = "maxCpBetMoney") val maxCpBetMoney: Long?,
    @Json(name = "maxParlayBetMoney") val maxParlayBetMoney: Long?,
    @Json(name = "verified") val verified: Int?, // 是否通过实名验证,0:未通过 1:已通过 2:验证中 3:验证失败
    @Json(name = "perBetLimit") val perBetLimit: Int?,
    @Json(name = "uwEnableTime") val uwEnableTime: Long? = 0,
    @Json(name = "maxPayout") val maxPayout: Double? = 0.0,
    @Json(name = "firstRechTime") val firstRechTime: String?,
    @Json(name = "currency") val currency: String?,
    @Json(name = "nationCode") val nationCode: String?,
    @Json(name = "liveSyncUserInfoVO") val liveSyncUserInfoVO: LiveSyncUserInfoVO?,
    @Json(name = "oddsChangeOption") val oddsChangeOption: Int?,
    @Json(name = "facebookBind") var facebookBind: Boolean,
    @Json(name = "googleBind") var googleBind: Boolean,
    @Json(name = "passwordSet") var passwordSet: Boolean,
    @Json(name = "vipType") var vipType: Int?,
    @Json(name = "placeOfBirth") var placeOfBirth: String?,
    @Json(name = "address") var address: String?,
    @Json(name = "permanentAddress") var permanentAddress: String?,
    @Json(name = "zipCode") var zipCode: String?,
    @Json(name = "permanentZipCode") var permanentZipCode: String?,
    @Json(name = "discountByGameTypeList") val discountByGameTypeList: List<UserGameTypeDiscount>?,
    val firstName: String?="",
    val middleName: String?="",
    val lastName: String?="",
    val birthday: String?="",
    val rejectRemark: String?="",
    val levelCode: String?=null,
    val mayaId: String?=null,
    val safeQuestionType: Int?=null,
    val fullVerified: Int?=null,//是否完全KYC认证，0为未完全认证，1为完全认证
)