package org.cxct.sportlottery.network.common


enum class PlayCode(val value: String) {
/*    SINGLE_BTS_H_Y("1X2&BTS-H-Y"),
    SINGLE_BTS_H_N("1X2&BTS-H-N"),
    SINGLE_BTS_D_Y("1X2&BTS-D-Y"),
    SINGLE_BTS_D_N("1X2&BTS-D-N"),
    SINGLE_BTS_C_Y("1X2&BTS-C-Y"),
    SINGLE_BTS_C_N("1X2&BTS-C-N"),*/
    SINGLE_FLG_H_H("1X2&FLG-H-H"),
    SINGLE_FLG_H_C("1X2&FLG-H-C"),
    SINGLE_FLG_D_H("1X2&FLG-D-H"),
    SINGLE_FLG_D_C("1X2&FLG-D-C"),
    SINGLE_FLG_C_H("1X2&FLG-C-H"),
    SINGLE_FLG_C_C("1X2&FLG-C-C"),
/*    SINGLE_OU_H_O("1X2&OU-H-O"),
    SINGLE_OU_H_U("1X2&OU-H-U"),
    SINGLE_OU_D_O("1X2&OU-D-O"),
    SINGLE_OU_D_U("1X2&OU-D-U"),
    SINGLE_OU_C_O("1X2&OU-C-O"),
    SINGLE_OU_C_U("1X2&OU-C-U"),*/
    DC_H_D("DC-H/D"),
    DC_C_D("DC-C/D"),
    DC_H_C("DC-H/C"),
/*    DC_BTS_HD_Y("DC&BTS-HD-Y"),
    DC_BTS_HD_N("DC&BTS-HD-N"),
    DC_BTS_CD_Y("DC&BTS-CD-Y"),
    DC_BTS_CD_N("DC&BTS-CD-N"),
    DC_BTS_HC_Y("DC&BTS-HC-Y"),
    DC_BTS_HC_N("DC&BTS-HC-N"),*/
    DC_FLG_HD_H("DC&FLG-HD-H"),
    DC_FLG_HD_C("DC&FLG-HD-C"),
    DC_FLG_CD_H("DC&FLG-CD-H"),
    DC_FLG_CD_C("DC&FLG-CD-C"),
    DC_FLG_HC_H("DC&FLG-HC-H"),
    DC_FLG_HC_C("DC&FLG-HC-C"),
/*    DC_OU_HD_O("DC&OU-HD-O"),
    DC_OU_HD_U("DC&OU-HD-U"),
    DC_OU_CD_O("DC&OU-CD-O"),
    DC_OU_CD_U("DC&OU-CD-U"),
    DC_OU_HC_O("DC&OU-HC-O"),
    DC_OU_HC_U("DC&OU-HC-U"),*/
    HT_FT_H_H("HT/FT-H/H"),
    HT_FT_H_D("HT/FT-H/D"),
    HT_FT_H_C("HT/FT-H/C"),
    HT_FT_D_H("HT/FT-D/H"),
    HT_FT_D_D("HT/FT-D/D"),
    HT_FT_D_C("HT/FT-D/C"),
    HT_FT_C_H("HT/FT-C/H"),
    HT_FT_C_D("HT/FT-C/D"),
    HT_FT_C_C("HT/FT-C/C"),
    OU_TTS1ST_O_H("OU-TTS1ST-O-H"),
    OU_TTS1ST_U_H("OU-TTS1ST-U-H"),
    OU_TTS1ST_O_C("OU-TTS1ST-O-C"),
    OU_TTS1ST_U_C("OU-TTS1ST-U-C"),
/*    LOSE_SEG1_CHAMP_H("LOSE-SEG1&CHAMP-H"),
    LOSE_SEG1_CHAMP_C("LOSE-SEG1&CHAMP-C"),
    WIN_SEG1_CHAMP_H("WIN-SEG1&CHAMP-H"),
    WIN_SEG1_CHAMP_C("WIN-SEG1&CHAMP-C"),
    OU_BTS_O_Y("OU&BTS-O-Y"),
    OU_BTS_O_N("OU&BTS-O-N"),
    OU_BTS_U_Y("OU&BTS-U-Y"),
    OU_BTS_U_N("OU&BTS-U-N"),*/
    OU_OE_O_O("OU&OE-O-O"),
    OU_OE_O_E("OU&OE-O-E"),
    OU_OE_U_O("OU&OE-U-O"),
    OU_OE_U_E("OU&OE-U-E"),
}